version: '3'

services:
  ghost:
    image: ghost:1-alpine
    ports:
      - 2368:2368
    depends_on:
      - db
    environment:
      MYSQL_CLIENT: mysql
      MYSQL_CONNECTION_HOST: db
      MYSQL_DATABASE: ghost
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    networks:
      - my-network
  db:
    image: mysql:5.7.40
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./db-data:/var/lib/mysql
    networks:
      - my-network  

volumes:
  db-data:

networks:
  my-network:
    driver: bridge
